{% set name = "cmip6_preprocessing" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f6c2a71580e2d68cc624b436150f4a77a9ddaa5f82d0e35abaf0c8215037467

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - xarray
    - pandas
    - numpy

test:
  imports:
    - cmip6_preprocessing

about:
  home: https://github.com/jbusecke/cmip6_preprocessing
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Some code to homogenize naming and parse variables in a xgcm compatible xarray dataset

  description: |
    Frustrated with how 'dirty' CMIP6 data still is? Do you just want to run a
    simple (or complicated) analysis on various models and end up having to
    write logic for each seperate case? Then this package is for you.

    Developed during the cmip6-hackathon this package provides utility
    functions that play nicely with intake-esm.
  dev_url: https://github.com/jbusecke/cmip6_preprocessing

extra:
  recipe-maintainers:
    - jbusecke
